name: Publish to Maven Central

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and test
        run: ./gradlew build

      - name: Publish package
        run: ./gradlew publish
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Close staging repository
        run: |
          curl -X POST \
            -H "Authorization: Bearer $(echo -n '${{ secrets.OSSRH_USERNAME }}:${{ secrets.OSSRH_PASSWORD }}' | base64)" \
            -H "Content-Type: application/json" \
            "https://ossrh-staging-api.central.sonatype.com/manual/upload/defaultRepository/io.github.wmnjuguna"